name: Python unittests
on: 
  push:
    paths:
    - '**/test/'
  workflow_dispatch:
jobs:
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python install
      uses: actions/setup-python@v4
      with: 
        python-version: 3.12

    - name: Run tests
      run: python -m unittest discover -p *Test.py
